export enum ActionType {
  ADD_GAME = "ADD_GAME",
  DELETE_GAME = "DELETE_GAME",
  GET_GAME_BY_ID = "GET_GAME_BY_ID",
  GET_GAME_BY_NAME = "GET_GAME_BY_NAME",
  GET_GAMES = "GET_GAMES",
  GET_GENRES = "GET_GENRES",
}
