export enum ActionType {
  ADD_GAME = "ADD_GAME",
  DELETE_GAME = "DELETE_GAME",
  FILTER_BY_GENRE = "FILTER_BY_GENRE",
  FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN",
  GET_GAME_BY_ID = "GET_GAME_BY_ID",
  GET_GAME_BY_NAME = "GET_GAME_BY_NAME",
  GET_GAMES = "GET_GAMES",
  GET_GENRES = "GET_GENRES",
  ORDER_BY_NAME = "ORDER_BY_NAME",
  ORDER_BY_RATING = "ORDER_BY_RATING",
}
